# Generated by Django 5.0.6 on 2024-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/media/brandLogo/'),
        ),
    ]
