# Generated by Django 5.0.6 on 2024-06-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
