# Generated by Django 5.0.6 on 2024-06-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='buyer_name',
            new_name='buyer',
        ),
    ]
